version: '3'

services:
    mysql:
        image: mysql:5.6
        ports:
            - 3306:3306
        volumes:
            - /var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        container_name: jens_mysql

    nginx:
        image: nginx:1-alpine
        ports:
            - 80:80
        volumes:
            - ./sites:/etc/nginx/conf.d
            - ~/Projects:/code
        depends_on:
            - php
        container_name: jens_nginx

    php:
        image: jenssegers/php:fpm
        volumes:
            - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ~/Projects:/code
        environment:
            XDEBUG_CONFIG: remote_host=172.16.1.10
        container_name: jens_php

    # blackfire:
    #     image: blackfire/blackfire
    #     environment:
    #         - BLACKFIRE_SERVER_ID
    #         - BLACKFIRE_SERVER_TOKEN

    # mongo:
    #     image: mongo
    #     ports:
    #         - 27017:27017
    #     volumes:
    #         - /data/db

    # redis:
    #     image: redis:alpine
    #     ports:
    #         - 6379:6379

    # influxdb:
    #     image: influxdb
    #     ports:
    #         - 8083:8083
    #         - 8086:8086

    # grafana:
    #     image: grafana/grafana
    #     ports:
    #         - 3000:3000
    #     links:
    #         - influxdb
